In [1]:
import pandas as pd

# ruta de tu archivo Excel y el nombre de la hoja

nombre_de_la_hoja = "BaseDatos"

df_colegios = pd.read_excel("BaseDatos.xlsx", sheet_name=nombre_de_la_hoja)


print(f"Se han leído exitosamente {len(df_colegios)} filas de colegios de la hoja '{nombre_de_la_hoja}'.")

# Muestra las primeras 5 filas para que tengas una idea de cómo se ven los datos.
print("\nPrimeras 5 filas de tu base de datos de colegios:")
print(df_colegios.head())

# Muestra un resumen general de las columnas, incluyendo los tipos de datos y si tienen valores nulos.
print("\nInformación de las columnas del DataFrame:")
df_colegios.info()

Se han leído exitosamente 2236 filas de colegios de la hoja 'BaseDatos'.

Primeras 5 filas de tu base de datos de colegios:
   No.  #_LOC MOMBRE_LOCALIDAD  DANE11_ESTABLECIMIENTO_EDUCATIVO  \
0    1      1          USAQUEN                      1.110010e+10
1    2      1          USAQUEN                      1.110013e+10
2    3      1          USAQUEN                      1.110013e+10
3    4      1          USAQUEN                      1.110013e+10
4    5      1          USAQUEN                      1.110013e+10

   DANE12_ESTABLECIMIENTO_EDUCATIVO NOMBRE_ESTABLECIMIENTO_EDUCATIVO  \
0                      111001000132      COLEGIO AQUILEO PARRA (IED)
1                      111001029955  COLEGIO AGUSTIN FERNANDEZ (IED)
2                      111001029955  COLEGIO AGUSTIN FERNANDEZ (IED)
3                      111001029955  COLEGIO AGUSTIN FERNANDEZ (IED)
4                      111001029955  COLEGIO AGUSTIN FERNANDEZ (IED)

   NIT  (DISTRITALES NIT FSE) DANE11_SEDE_EDUCATIVA  DANE12_SEDE_EDUCATIVA  \
0                8.001053e+09           11100100136           111001000132
1                8.300929e+08           11100129959           111001029955
2                8.300929e+08           11184800243           111848000244
3                8.300929e+08           11184803455           111848003456
4                8.300929e+08                   NaN           111001800920

  NOMBRE_SEDE_EDUCATIVA  ...       CHIP_1    CPF  ESTRATO_GEO No_UPZ  \
0         AQUILEO PARRA  ...  AAA0142LBRJ  115.0  SIN ESTRATO      9
1     AGUSTIN FERNANDEZ  ...  AAA0115LEWF  114.0  SIN ESTRATO     13
2          SAN BERNARDO  ...  AAA0115HUFT  128.0            1     11
3    SANTA CECILIA ALTA  ...  AAA0157OEBS  129.0            1     11
4          LOS PISINGOS  ...          NaN    NaN          NaN     11

            NOMBRE_UPZ SECTOR_CENSAL COORDENADA LONGITUD (X)  \
0             VERBENAL        008527              -74.039171
1           LOS CEDROS        008520              -74.024102
2  SAN CRISTOBAL NORTE        008520              -74.017673
3  SAN CRISTOBAL NORTE        008535              -74.016165
4  SAN CRISTOBAL NORTE           NaN              -74.024458

  COORDENADA LATITUD (Y) NUMERO_UPL  NOMBRE UPL
0               4.765726          26    TOBERIN
1               4.729647          26    TOBERIN
2               4.732533          26    TOBERIN
3               4.735055          26    TOBERIN
4               4.733539          26    TOBERIN

[5 rows x 43 columns]

Información de las columnas del DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2236 entries, 0 to 2235
Data columns (total 43 columns):
 #   Column                                                              Non-Null Count  Dtype
---  ------                                                              --------------  -----
 0   No.                                                                 2236 non-null   int64
 1   #_LOC                                                               2236 non-null   int64
 2   MOMBRE_LOCALIDAD                                                    2236 non-null   object
 3   DANE11_ESTABLECIMIENTO_EDUCATIVO                                    2026 non-null   float64
 4   DANE12_ESTABLECIMIENTO_EDUCATIVO                                    2236 non-null   int64
 5   NOMBRE_ESTABLECIMIENTO_EDUCATIVO                                    2236 non-null   object
 6   NIT  (DISTRITALES NIT FSE)                                          2234 non-null   float64
 7   DANE11_SEDE_EDUCATIVA                                               2000 non-null   object
 8   DANE12_SEDE_EDUCATIVA                                               2236 non-null   int64
 9   NOMBRE_SEDE_EDUCATIVA                                               2236 non-null   object
 10  CONSECUTIVO                                                         2236 non-null   int64
 11  ORDEN DE SEDE                                                       2236 non-null   object
 12  SECTOR                                                              2236 non-null   object
 13  CLASE                                                               2236 non-null   object
 14  PRESTADOR DEL SERVICIO                                              2236 non-null   object
 15  ESTADO                                                              2236 non-null   object
 16  ZONA                                                                2236 non-null   object
 17  DIRECCION-GEO                                                       2236 non-null   object
 18  BARRIO-GEO                                                          2228 non-null   object
 19  TELEFONO                                                            2236 non-null   object
 20  CORREO ELECTRONICO                                                  2236 non-null   object
 21  WEB                                                                 1187 non-null   object
 22  CODIGO POSTAL                                                       2236 non-null   object
 23  CALENDARIO                                                          2236 non-null   object
 24  GENERO                                                              2236 non-null   object
 25  CARACTER PARA LA MEDIA                                              1264 non-null   object
 26  ESPECIALIDAD PARA LA MEDIA                                          1264 non-null   object
 27  ENFASIS PARA EL CARACTER ACADEMICO DE LA MEDIA                      154 non-null    object
 28  RECTOR/DIRECTOR (COLEGIOS DISTRITALES ACTUALIZACION A 09-SEP-2024)  2236 non-null   object
 29  CAPACIDADES EXCEPCIONALES                                           1004 non-null   object
 30  GRUPOS ETNICOS                                                      1221 non-null   object
 31  BILINGÜISMO                                                         58 non-null     object
 32  REGIMEN Y CATEGORIA DE COSTOS                                       1457 non-null   object
 33  CHIP_1                                                              718 non-null    object
 34  CPF                                                                 679 non-null    float64
 35  ESTRATO_GEO                                                         2192 non-null   object
 36  No_UPZ                                                              2236 non-null   object
 37  NOMBRE_UPZ                                                          2236 non-null   object
 38  SECTOR_CENSAL                                                       2227 non-null   object
 39  COORDENADA LONGITUD (X)                                             2236 non-null   object
 40  COORDENADA LATITUD (Y)                                              2236 non-null   object
 41  NUMERO_UPL                                                          2236 non-null   int64
 42  NOMBRE UPL                                                          2236 non-null   object
dtypes: float64(3), int64(6), object(34)
memory usage: 751.3+ KB

In [7]:
df_suba = df_colegios[df_colegios["MOMBRE_LOCALIDAD"] == "SUBA"]
print(df_suba.head())

       No.  #_LOC MOMBRE_LOCALIDAD  DANE11_ESTABLECIMIENTO_EDUCATIVO  \
1260  1261     11             SUBA                      1.110010e+10
1261  1262     11             SUBA                      1.110010e+10
1262  1263     11             SUBA                      1.110012e+10
1263  1264     11             SUBA                      1.110012e+10
1264  1265     11             SUBA                      1.110013e+10

      DANE12_ESTABLECIMIENTO_EDUCATIVO  \
1260                      111001002330
1261                      111001002330
1262                      111001015776
1263                      111001015776
1264                      111001025020

                       NOMBRE_ESTABLECIMIENTO_EDUCATIVO  \
1260                           COLEGIO LA GAITANA (IED)
1261                           COLEGIO LA GAITANA (IED)
1262  COLEGIO INSTITUTO TECNICO DISTRITAL JULIO FLOR...
1263  COLEGIO INSTITUTO TECNICO DISTRITAL JULIO FLOR...
1264               COLEGIO ALBERTO LLERAS CAMARGO (IED)

      NIT  (DISTRITALES NIT FSE) DANE11_SEDE_EDUCATIVA  DANE12_SEDE_EDUCATIVA  \
1260                8.300245e+09           11100102333           111001002330
1261                8.300245e+09           11100144281           111001044288
1262                8.300791e+09           11176900352           111769000352
1263                8.300791e+09           11100115770           111001015776
1264                8.300026e+09           11100125023           111001025020

       NOMBRE_SEDE_EDUCATIVA  ...       CHIP_1     CPF  ESTRATO_GEO No_UPZ  \
1260              LA GAITANA  ...  AAA0141TSXS  1113.0  SIN ESTRATO     71
1261             VILLA MARIA  ...  AAA0132OJZE  1135.0            2     71
1262              SANTA ROSA  ...  AAA0058ONAF  1141.0            3     25
1263            JULIO FLOREZ  ...  AAA0059ADXS  1109.0            4     25
1264  ALBERTO LLERAS CAMARGO  ...  AAA0129FUWW  1138.0            2     28

       NOMBRE_UPZ SECTOR_CENSAL COORDENADA LONGITUD (X)  \
1260    TIBABUYES        009257               -74.10861
1261    TIBABUYES        009214              -74.106603
1262  LA FLORESTA        005402              -74.074113
1263  LA FLORESTA        005403              -74.077564
1264    EL RINCON        009209               -74.10248

     COORDENADA LATITUD (Y) NUMERO_UPL       NOMBRE UPL
1260               4.742218          10       TIBABUYES
1261               4.739903          10       TIBABUYES
1262               4.695955          27            NIZA
1263               4.687194          27            NIZA
1264               4.743485          28  RINCON DE SUBA

[5 rows x 43 columns]

In [8]:
conteo_por_localidad = df_colegios.groupby('MOMBRE_LOCALIDAD').size().reset_index(name='Cantidad_Colegios')

print("\n--- Conteo de Colegios por Localidad ---")
# Ordenamos la tabla para ver las localidades con más colegios primero (de mayor a menor).
x = conteo_por_localidad.sort_values(by='Cantidad_Colegios', ascending=False)
print(x)

--- Conteo de Colegios por Localidad ---
      MOMBRE_LOCALIDAD  Cantidad_Colegios
14                SUBA                362
7              KENNEDY                264
5             ENGATIVA                258
2                 BOSA                147
4       CIUDAD BOLIVAR                147
18             USAQUEN                132
12       SAN CRISTOBAL                128
11  RAFAEL URIBE URIBE                123
19                USME                109
10       PUENTE ARANDA                100
6             FONTIBON                 98
17          TUNJUELITO                 69
1       BARRIOS UNIDOS                 63
16         TEUSAQUILLO                 59
0       ANTONIO NARIÑO                 43
9         LOS MARTIRES                 36
13             SANTAFE                 29
3            CHAPINERO                 26
15             SUMAPAZ                 24
8        LA CANDELARIA                 19